version: "3"
services:
  web:
    image: xyz_books
    build:
      context: .
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    restart: always
  mysql:
    image: mysql:8.0.33
    container_name: xyz_books_db_container
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysqld
volumes:
  db_data:
